apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: image-registry
      type: string
    - name: path-to-context
      type: string
      default: "."
    - name: path-to-dockerfile
      type: string
      default: "./Dockerfile"
  tasks:
    - name: npm-install
      taskRef:
        name: npm-install-task
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: run-tests
      taskRef:
        name: jasmine-test-task
      runAfter:
        - npm-install
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - run-tests
      params:
        - name: IMAGE
          value: "$(params.image-registry)"
        - name: CONTEXT
          value: "$(params.path-to-context)"
        - name: DOCKERFILE
          value: "$(params.path-to-dockerfile)"
      workspaces:
        - name: source
          workspace: pipeline-workspace
